sonar.projectKey=NataliaZepeda_RetailQA
sonar.organization=nataliazepeda

# Nombre y ruta del proyecto
sonar.projectName=RetailQA
sonar.sources=.

# Carpetas a excluir del análisis (dependencias, no código propio)
sonar.exclusions=node_modules/**,**/node_modules/**
